general:
  front_end:
    _type: a2a
    name: "Monitoring Agent"
    description: "Monitoring Agent for RAN p0nominal Optimization"
    host: 0.0.0.0
    port: ${PORT:-9900}
    version: "1.0.0"
    max_concurrency: 1
  telemetry:
    tracing:
      phoenix:
        _type: phoenix
        endpoint: http://localhost:6006/v1/traces
        project: monitoring
      local_file:   
        _type: file  
        output_path: ./traces/traces.jsonl
        project: monitoring
        level: DEBUG


workflow:
  _type: langgraph_wrapper
  dependencies:
    - .
  graph: main.py:agent
