GET http://localhost:9203/.well-known/agent.json

###

POST http://localhost:9203
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "message/stream",
  "params": {
    "configuration": {
      "accepted_output_modes": [
        "text"
      ]
    },
    "message": {
      "context_id": "8f01f3d172cd4396a0e535ae8aec6682",
      "message_id": "1",
      "role": "user",
      "parts": [
        {
          "type": "text",
          "text": "I want to validate a P0 nominal of -80. My current P0 nominal is -100."
        }
      ]
    }
  }
}
